print('-='*30)
print('Vinte primeiros colados na Tabela do Brasileirão')
print('-='*30)
equipa = ('São Paulo', 'Flamengo', 'Atlético-MG', 'International', 'Grêmio', 'Palmeiras', 'Fluminense', 'Santos', 'Corinthians', 'Ceará SC', 'Atlético-GO', 'Atlético-PR', 'Bragantino', 'Fortaleza', 'Sport Recife', 'Bahia', 'Vasco da Gama', 'Botafogo', 'Coritiba', 'Goiás')
print(f'Os 5 primeiros colocados foram {equipa[0:5]}')
print('-='*30)
print(f'Os últimos 4 colacados foram {equipa[16:]}')
print('-='*30)
print(f'Os vinte primeiros colacados pela ordem alfabética fica {sorted(equipa)}')
print('-='*30)
print('O Grêmio encontrasse na {}ª posição'.format(equipa.index('Grêmio')))
